---
language: objective-c

before_script:
  - sudo easy_install cpp-coveralls

script:
  - xctool -workspace 'Mod.xcworkspace' -scheme 'Mod' -configuration Debug -sdk iphonesimulator6.0 clean build test ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
  - ./script/coveralls.sh